; Duckoustic v0.2.2
; ESP32-S3 optical microphone — SoftAP HTTPS + stereo PAM + optical playback

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDUCK_VERSION=\"0.2.2\"
    -I include
lib_ldf_mode = deep+
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    fhessel/esp32_https_server @ 1.0.0
    fhessel/esp32_https_server_compat @ 1.0.0
